//This file is generated by VisualGDB and is used to get accurate IntelliSense
#pragma once
#include <Arduino.h>

#define SYSPROGS_ARDUINO_EXPAND_GENERATED_PROTOTYPES \
	void setup(); \
	void loop(); \
	void DHTbegin(uint8_t pin); \
	float ReadTemperature(); \
	float readHumidity(); \
	bool read(); \
	uint32_t expectPulse(bool level); \

